version: '3.4'
services:
  minio:
    image: minio/minio
    entrypoint: [""]
    command: ["sh", "-c", "mkdir -p /data/phlare && minio server --quiet /data --console-address=:9002"]
    environment:
      - MINIO_ROOT_USER=phlare
      - MINIO_ROOT_PASSWORD=supersecret
    volumes:
      - minio-data:/data
    ports:
      - 9002:9002

  grafana:
    image: grafana/grafana:main
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DIAGNOSTICS_PROFILING_ENABLED=true
      - GF_DIAGNOSTICS_PROFILING_ADDR=0.0.0.0
      - GF_DIAGNOSTICS_PROFILING_PORT=6060

    volumes:
      - ./config/grafana-provisioning-dashboards.yaml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      - ./config/grafana-provisioning-datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
    ports:
      - 3000:3000

  load-balancer:
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "phlare-1"
      - "phlare-2"
      - "phlare-3"
    ports:
      - 4100:4100

  phlare-1:
    image: grafana/phlare:latest
    command: ["-config.file=/etc/phlare/config.yaml"]
    depends_on:
      - minio
    volumes:
      - ./config/phlare.yaml:/etc/phlare/config.yaml
      - phlare-1-data:/data
    ports:
      - 4101:4100

  phlare-2:
    image: grafana/phlare:latest
    command: ["-config.file=/etc/phlare/config.yaml"]
    depends_on:
      - minio
    volumes:
      - ./config/phlare.yaml:/etc/phlare/config.yaml
      - phlare-2-data:/data
    ports:
      - 4102:4100

  phlare-3:
    image: grafana/phlare:latest
    command: ["-config.file=/etc/phlare/config.yaml"]
    depends_on:
      - minio
    volumes:
      - ./config/phlare.yaml:/etc/phlare/config.yaml
      - phlare-3-data:/data
    ports:
      - 4103:4100
  
  agent:
    image: grafana/phlare:latest
    command: ["-config.file=/etc/phlare/agent.yaml", "-log.level=debug"]
    depends_on:
      - minio
    volumes:
      - ./config/agent.yaml:/etc/phlare/agent.yaml

volumes:
  phlare-1-data:
  phlare-2-data:
  phlare-3-data:
  minio-data:
