apiVersion: 1
datasources:
  - access: proxy
    basicAuth: false
    editable: true
    isDefault: true
    name: phlare
    type: phlare
    uid: phlare
    url: http://load-balancer:4100
    version: 1
    jsonData:
      httpHeaderName1: 'X-Scope-OrgID'
    secureJsonData:
      httpHeaderValue1: 'demo'