multitenancy_enabled: true

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist 
      replication_factor: 3

memberlist:
  join_members: [phlare-1, phlare-2, phlare-3]

phlaredb:
  data_path: /data/ingester

tracing:
  enabled: false

storage:
  backend: s3
  s3:
    endpoint: minio:9000
    access_key_id: phlare
    secret_access_key: supersecret
    insecure: true
    bucket_name: phlare